gdrive.version=${project.version}
gdrive.file.upload.retries=3
gdrive.core.drive.redirectUri.port=8783
gdrive.core.drive.redirectUri.context=/gdrive
gdrive.core.drive.redirectUri=http://127.0.0.1:${gdrive.core.drive.redirectUri.port}${gdrive.core.drive.redirectUri.context}